#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Taking stock and tracking progress
tags:  ""
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

When starting the spring semester, students are frequently a little
rusty. They just had a high intensity month of study, tests, and
projects. That was followed by a week of nothing.

I like to start with something lightweight that gets them coding again
and ramps them up to speed.

In SoftDev I started with a brief overview of the HTML5 canvas and
then gave them a small homework assignment to do something fun.

I also remind the kids to self assess where they are and how they've
developed as a programmer. 

I get a little tired of education "experts" espousing nonsense like you
have to have each talk each day or that you need to assess each kid
multiple times a period. That's nonsense. With 34 kids in a 40 minute
class and 150 kids a day, that doesn't fly. Besides, so many concepts
take time to develop, learn, and absorb. 

Yes, you can get some instant and short term feedback but a lot more
is revealed over time.

I'm attaching a small sampling of their homework assignments. It was
basically a one day assignment to do something fun with the HTML5
canvas and indeed, it looks like they had fun.

I asked the kids to reflect on what they did now and what they could
do a semester, two, and three semesters ago.

In the beginning they would have had no idea how to approach any of
these. A year ago, they would be a major project. Now, they can knock
these out as a homework assignment. 

Once you take a step back to look at how much a student can grow in a
year or so you have to marvel at the results.

At a place like Stuy, the kids frequently and unfairly judge themselves against
super prodigies. 

I'm hoping by looking back at what they could do then vs now they'll
appreciate how awesome they are.

All sources at [[https://github.com/stuycs-softdev/submissions]]

Enjoy...

* Chain reaction
** click to start the reaction
*** by Nadia and Sophie
#+begin_html
<iframe height=600 width="80%"
src="https://cdn.rawgit.com/stuycs-softdev/submissions/master/6/canvas/sophie-nadia/canvas.html"
>
</iframe>
#+end_html

* MakeOver Party
** Take a picture and apply virtual makeup
*** by Veronika and Miranda
#+begin_html
<iframe height=800 width="80%"
src="https://cdn.rawgit.com/stuycs-softdev/submissions/master/7/canvas/miranda-veronika/canvas.html"
>
</iframe>
#+end_html


* 3D Depth Perception Pong
** Follow the ball and keep it in the well
*** by Natan
#+begin_html
<iframe height=800 width="80%"
src="https://cdn.rawgit.com/stuycs-softdev/submissions/master/6/canvas/NZamansky/index.html"
>
</iframe>
#+end_html

* Can't really describe this but I love it
** Use WASD to move DW around
** by Fish
#+begin_html
<iframe height=800 width="80%"
src="https://cdn.rawgit.com/stuycs-softdev/submissions/master/6/canvas/fishy/dyrlandland.html"
>
</iframe>
#+end_html

