#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Student Projects 2014 - Let's go to the video tape
tags:   Lisp Google Development Vimeo HTML Emacs Markup Languages Data Formats
---
#+end_html

#+begin_html

<style>
div.center {text-align:center;}
</style>
#+end_html

Just completed the second time through for my Software Development
course. Last year we had a great time at our Demo Night hosted at
Google.

This year, unfortunately, due to a variety of reasons, we couldn't get
the event together. Still, the kids did great work so I thought I'd
share.

This year, I asked each group to make a short video.

First up, we've got bit<<shift - a search engine for code. Nice idea
and a really slick interface.

#+BEGIN_HTML
<div class="center">
<iframe src="//player.vimeo.com/video/98697078" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="http://vimeo.com/98697078">bitshift: a source code search engine</a> from <a href="http://vimeo.com/ear">Ben Kurtovic</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
</div>
#+END_HTML


Next up, we've got Socialpedia - our answer to Klout -


#+BEGIN_HTML
<div class="center">
<iframe width="560" height="315" src="//www.youtube.com/embed/uhLZBsZWQGk" frameborder="0" allowfullscreen></iframe>
</div>
#+END_HTML

And then Twitch Rock-em-Sock-em Robots - 

#+BEGIN_HTML
<div class="center">
<iframe width="560" height="315"
src="//www.youtube.com/embed/Am3PTB_FvNs" frameborder="0"
allowfullscreen></iframe>
</div>
#+END_HTML

There were a bunch of other neat projects including a site that
crowd-sources 311 trash related problems and a version of the game
"Frozen Synapse" where you can program your forces using an embedded
Lisp interpreter.

Very cool stuff.

Good job guys!!!!!
