#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Boys, Girls, Arts, Tech, and Vacation
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

Spent most of vacation relaxing. Finished off the remaining college
recs, tried to catch up on sleep, and worked on a few project.

We've had an interesting December break dynamic in our household for
the past few years. My son, Natan is very much into his music, both as
a performer and a composer. A few years ago we discovered [[http://www.livingtraditions.org/docs/index_kk.htm][KlezKamp]]. It
spoke to both Natan and Devorah. Batya, coming back from college
wasn't so into it and I was somewhat indifferent. 

The end result is that for most of the first half of the break, Batya
and I were left on our own in the city while Natan and Devorah were up
in the Catskills. 

So, what did we do? In addition to playing tourist, we rebuilt the
CSTUY web site (with a little help from her boyfriend Zach) - check it
out: [[http://cstuy.org][cstuy.org]]. I'm really happy with the result and now have a code
base that I'm happy with and can maintain.

I can't describe how awesome it is to be able to collaborate on
something real with ones daughter and I hope we can work on more
projects in the future. 

Of course, I had my Natan time when he and Devorah got home. We spent
new years eve at the [[http://nygasp.org/][NYGASP]] production of HMS Pinafore. Natan loves
opera and is something of a Savoyard and he's also a terrific
singer. Something he must have inherited from my father, although he
never met him.

So, we had our own project:

#+begin_html
<iframe width="100%" height="450" scrolling="no" frameborder="no"
src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/184357024&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
#+end_html

His is the good voice singing Dick Deadeye and I'm the not so good one
doing Captain Corcoran. We recorded it A Capella and he added the midi
after the fact. I think he had to change the key and I'm sure he had
to mess with the tempo.

Some of you might have noticed that I worked on the tech project with
Batya and the artsy one with Natan but don't worry - Natan's planning
on majoring in [[https://github.com/NZamansky][Computer Science]] and Batya's the musical director and
an alto in [[http://www.thechainotes.com/][The
Chai Notes]] up at Cornell. 

So that was my break. Back to work in a couple of days.




