#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Alan Alda on Teaching Science
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

Scale, scale, scale. Scripted lessons. Online resources, Moocs. No
excuses schools. All of these are modern trends in education. None of
these are about good education. It's really demoralizing reading
article after article devaluing true master teachers and real
education. 

So, last night was a real pleasure.
 
I attended a talk, given by Alan Alda on communicating science. The
talk was sponsored by [[http://academyforteachers.org/][The Academy for Teachers]]. I grew up watching
Hawkeye on MASH and more recently Arnold Vinick on The West Wing but
Mr. Alda has really been keeping himself busy in the world of
education. Check out what he's doing at the [[http://www.centerforcommunicatingscience.org/][Alan Alda Center for
Communicating Science]] at Stoney Brook University.

At it's core, Mr. Alda's talk was about teaching. Making a connection
with your students and engaging them. The exact opposite of many of
the current ed reform trends.

Mr. Alda talked about [[http://www.centerforcommunicatingscience.org/the-flame-challenge-2/][the Flame Challenge]] where he challenged
scientists to teach 11 year olds all about [[https://en.wikipedia.org/wiki/The_Chemical_History_of_a_Candle][a candle]] without dumbing it
down. Communication.

He also talked about story telling. At one point he had a volunteer
from the audience carry a glass across the stage. He then had her do
it again, but this time with a full glass telling her "if you spill a
drop everyone in your village will die." The difference in audience
attention was striking.

Mr. Alda also talked about using improvisational games to help
students open up as well as about [[https://en.wikipedia.org/wiki/Curse_of_knowledge][the curse of knowledge.]]

One of my favorite parts of the talk was when an audience member asked
for a few teaching tips. He replied that he hates tips because out of
context, without the connection to the class, they're
meaningless. Mr. Alda used as an example:

#+BEGIN_QUOTE
Imagine that you're about to give a piano recital at Carnegie Hall 
and you asked for a few tips.

If you've never played before, those tips aren't going to help you.
#+END_QUOTE

I'm asked for CS teaching tips all the time, and Mr. Alda very much
captured my feelings on the subject. My friend and Colleague Jim
Cocoros also captured the feeling when he reminded me that the only
"tip" he gives new teachers is "be yourself." I couldn't agree more.

It was a delightful and a refreshing evening. I very much appreciate
and admire what Mr. Alda is doing beyond his acting and while I very
much hope he's able to extend his reach to more high school teachers
as he continues to work on communicating in science.
