#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Finding the Bell Tower
tags:  
---
#+end_html


No Edu-Rant today nor a clever lesson plan.

I just thought I'd share an email exchange that cracked me up. 


We're out in Ann Arbor visiting our son Natan who is in his first year at Michigan.

Devorah sent an email asking where we should meet.

It turns out that Natan's last class of the day is Music Composition. 

Here's what followed:


**Natan:**

#+BEGIN_QUOTE

Composition is in the bell tower on Central. It's hard to miss. It's a
bell tower. It's right by Hill Auditorium, and looks like a bell
tower. It also sounds like a bell tower at certain points in the day,
but I don't think I've heard it sound like a bell tower around the end
of class, so you're probably better off looking for the thing that
looks like a bell tower rather than listening for the thing that
sounds like a bell tower. I would assume it also smells and tastes
like a bell tower, but if you're in close enough proximity to smell or
taste the bell tower, I think you've probably found the bell tower. It
looks like a huggable building, but please, dad, do not hug the bell
tower. I have class there.

#+END_QUOTE


**Devorah:**
#+BEGIN_QUOTE

We can meet you at the bell tower as long as we can figure out what it
looks like.  Can you please give us a detailed description? Maybe
you should taste it just in case.  Does the bell tower on Central
smell like the bell tower on North?
#+END_QUOTE

**Natan:**
#+BEGIN_QUOTE

The bell tower is around the size and shape of a bell tower. It's ten
stories high, with the first nine stories being a little less than
one-tenth of a bell tower tall, and the tenth being rather more than
one-tenth of a bell tower tall (the tenth story being where the bells
are). The width is about equal to that of a bell tower. It has two
doors, one on one side of the bell tower, and the other on the other
side of the bell tower. It has clock faces on top, which should, at
the point you see it, resemble a clock face indicating the time which
it is. (The appearance of the clock faces should update in near-real
time.) If you stick around long enough, it should start to sound like
a bell tower, or perhaps like a monster descending the stairs singing
Gilbert and Sullivan. I don't know what the bell tower on North smells
like because the bell tower on North is currently blocked off. But it
also resembles a bell tower, being approximately the same size and
shape of a bell tower. It is much less likely to sound like a bell
tower, though.
#+END_QUOTE
