#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Announcing def hacks("Winter",2015):
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

Last March, we (CSTUY) hosted our first hackathon - def hacks():

It was a tremendous success. Fifty students of all experience levels,
a bunch of great mentors and judges - added all together and it was a
terrific day.

I wrote about it [[http://cestlaz.github.io/2015/03/29/defhacks.html#.VkFAN5_0-Ak][here]].

We're doing it again. We love last years hosts [[http://sumall.com][SumAll]] and are grateful
that they continue to host our Saturday [[http://cstuy.org/programs/hacking_sessions][Hacking Sessions]] but we are
also grateful to Facebook NY for allowing us to use their larger space for
this edition of def hacks(). Larger space = more hackers.

So, if you're a high school student who wants to spend a fun day
building something cool or if you know one, more information and
registration can be found here:


[[http://defhacks.com][def hacks("Winter",2015):]]




