#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Using easy assignments to introduce deep concepts
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

In this early part of the semester, the students don't know all that
much. We haven't covered that many language constructs let along
algorithms, development techniques and all that other good stuff.

In terms of the "Java" part of APCS we've talked about basic types,
Strings, basic classes, loops and conditionals. We're limited in the
tools we have but we can still get the classes thinking in the right
way.

Last week, when we introduced loops we spent some time drawing shapes.

Starting with things like

#+BEGIN_HTML
Rectangle:
<pre>
*****
*****
*****
</pre>
#+END_HTML

and

#+BEGIN_HTML
Triangle1
<pre>
*
**
***
****
*****
</pre>
#+END_HTML

Simple nested loop stuff.

#+BEGIN_SRC java
String s = "";
for (int r = 0; r < height; r++) {
  for (int c=0; c<=r; c++ ){
    s=s+"*";"
  }
  s=s+"\n";
}
return s;
#+END_SRC

Things get interesting when we looked at the next one:

#+Name: Triangle2
#+BEGIN_HTML
Triangle2:
<pre>
    *
   **
  ***
 ****
*****
</pre>
#+END_HTML

It seems like a simple little problem with a simple solution:

What I love about it is that you can look at it in a couple of
interesting ways.

First, you can look at those spaces as a triangle in and of
themselves (replaced with # below):

#+BEGIN_HTML
<pre>
####*
###**
##***
#****
*****
</pre>
#+END_HTML

Well, that's almost the same as the Triangle1 from above. Also, if you
take away that triangle of spaces, you're pretty much left with
Triangle1.

The structure of the code can look something like:
#+BEGIN_SRC java
String s="";
for (int r = 0; r < height; r++){
  // loop over the number of spaces we need for this line

  // loop over the number of stars we need for this line

  s=s+"\n";
}
return s;
#+END_SRC

We can also look at the problem just as a series of lines. How many
spaces and how many stars:


Let's say height = 5
#+BEGIN_SRC org :results html
| row | spaces | stars |
|-----+--------+-------|
|   0 |      4 |     1 |
|   1 |      3 |     2 |
|   2 |      2 |     3 |
|   3 |      1 |     4 |
|   4 |      0 |     5 |
|-----+--------+-------|
|   r |  h-r-1 |   r+1 |
|-----+--------+-------|
#+END_SRC

Once we see the relationships between height (h) and row (r) for each
level, we're led to:

#+BEGIN_SRC java
String s="";
for (int r = 0; r < height; r++){
  for (int c = 0 ; c < height - r - 1; c++)
    s=s+" ";
  for (int c = 0 ; c<r+1; c++)
    s=s+"*";
  s=s+"\n";
}
return s;
#+END_SRC

We then looked at:

#+BEGIN_HTML
Triangle3:
<pre>
   *
  ***
 *****
*******
</pre>
#+END_HTML

We worked it the same way but also noted that we could take a cheesy
approach to the number of stars on each line. We could start with
numStars=1 and then at the end of the loop, do numStars =
numStars + 2. 

I say it's a cheesy solution, but the point is some times you can come
up with a formula (as in the able above) other times you just see how
to change things between iterations.

The final problem was this:

#+BEGIN_HTML
<pre>
   *
  ***
 *****
  ***
   *
   
</pre>
#+END_HTML

This time the class noticed that they could start with just calling
Triangle3 and then taking a copy of the Triangle3 code and tweaking
it.

This led to a talk of refactoring and ultimately writing  line
routine:

#+BEGIN_SRC java
public String line(String c, int num){
  String s="";
  for (int i=0;i<num;i++)
    s=s+c;
  return s;
}
#+END_SRC

Yes, I know we can just do "*"*num but the idea is to get the kids
thinking about things in the right way. On top of just playing with
nested loops, we dealt with:

- Looking at problems in multiple ways.
- Coming up with formulas and also just brute force tweaking.
- Re-using existing code.
- refactoring.

Not a bad set of classes.
