#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: I guess some people like the blues
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html


Funny story from yesterday.

Devorah, my better half, is an assistant principal at another high
school. Yesterday evening, she was at work late for "curriculum
night." Parents came to the school after hours to hear a variety of
presentations.

During her presentation, Devorah mentioned her name, that she had two
former public school kids in college, and that's about it for the
personal info.

After the session, two parents approached Devorah to say "we're big
fans of your husband!"

Since when do teachers have fans?????????

I mean, I understand "my daughter/son was in your husbands class and
really enjoyed it," but "I'm a big fan?" She wasn't sure how to take
it. Obviously we both took it as an honor and compliment but we also
both got a chuckle out of the turn of phrase.

I've already said that teachers aren't [[http://cestlaz.github.io/2014/12/14/rockstar-godfather.html#.Vg264t8Sr0o][rock stars, we're blues men]] so
I guess this shows that some folks still like the blues.


