#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Halloween 2015 - the video
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

As a teacher, sometimes your gut tells you to do something and it
turns out to be a really good idea.

That's what happened in October, 1994. I decided to dress up as [[https://en.wikipedia.org/wiki/Groo_the_Wanderer][Groo
the Wanderer]] for Halloween. I never dressed in costume for school
before and back then, no many did. A few students and very few
teachers.

Afterwards, I noticed that my younger students - the ones that didn't
know me that well yet, really loosened up and so a tradition was born.

Over each of the next 20 Halloweens, I did something
different. Sometimes solo, sometimes as a pair and more recently as
part of a team.

What started as a lark has now become something of an obligation but
it's still fun.

So, with no further ado, let's go to the video tape:


#+begin_html
<div class="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/81qHI-iNkXg" frameborder="0" allowfullscreen></iframe>
</div>
#+end_html

And of course, the full playlist:


#+begin_html
<div class="center">
<iframe width="560" height="315" src="//www.youtube.com/embed/videoseries?list=PL9KxKa8NpFxJYgovyJhF4HZRsAqYKBLiG" frameborder="0" allowfullscreen></iframe>
</div>
#+end_html

