#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: I hate ruby or why I'm switching blogging platforms
tags:  
---
#+end_html

I'm moving to a new blogging platform. I'm still going to use GitHub
pages but after a few years of using [[https://jekyllrb.com/][Jekyll]], I'm switching to [[https://getnikola.com/][Nikola]].

I think I've got the move worked out but if you're reading this via an
rss or atom reader, make sure to check back in a couple of days - you
might have to re-subscribe.

Why am I switching?

Beccause I hate Ruby. 

Ok, not really - I barely know the language. I was already a  Python
guy when Ruby came along and I didn't see any real added value to
switching. 

This isn't really about Ruby though, it's really about the Ruby
ecosystem and how that which we don't know is strange and frightening

#+BEGIN_HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/LV0wTtiJygY" frameborder="0" allowfullscreen></iframe>
#+END_HTML

I started using Jekyll because that's what was supported by GitHub
pages. It's fairly simple and it basically worked. It had a few
warts, specifically, I've had problems getting org-mode blog posts to
publish just the way I'd like and it's hard to debug when a post has
some bad markup in it, but it got the job done. 

Recently, though, I've had to reinstall Jekyll a number of  times and
for me, that's been a nightmare.

One is supposed to just be able to **sudo gem install jekyll**.

Ok, so you need some packages installed:

#+BEGIN_SRC bash
sudo apt-get install ruby-dev 
#+END_SRC

But I've got ruby 1.9 and I need ruby 2 point something. Ok:

#+BEGIN_SRC bash
sudp apt-get install ruby2.0 ruby2.0-dev
#+END_SRC

But that fails since we're still running 1.9. Every time I look for a
solution I go down the ruby ecosystem rabbit hole. 

All I want is Jekyll!!!!!!

Why can't I just **pip install jekyll** like I can do with Python
packages!!!!!

nothing wrong with ruby ecosystem I'm just nnot familiar

using python for years

Garth and Alfred

and cloud vs ide

