#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title:  Teacher Ratings
tags:  
---
<style>
div.center {text-align:center;}
</style>
#+end_html

* 
A while back I posted about the new teacher evaluation system in New York.

* 
I originally wrote about the system [[http://cestlaz.github.io/2013/09/06/why_i_might_no_longer_be_an_effective_teacher.html#.VAZVNR_GyzU][here]] and a little more [[http://cestlaz.github.io/2013/10/25/effective-teacher-2.html#.VAZVMx_GyzU][here.]]
* 
Well, the results are in and I got my evaluation. What type of teacher
am I? According to New York City I'm "Effective," which is basically
run of the mill.

* 
Let's look a little deeper. At the end of the day, each teachers
receive a numeric score from 0 to 100. The score maps to a grade as
follows:

|----------------------+----------------------|
| <20>                 | <20>                 |
| 0 - 64               | Ineffective          |
| 65 - 74              | Developing           |
| 75 - 90              | Effective            |
| 91 - 100             | Highly Effective     |
|----------------------+----------------------|

With "Effective" being pretty much the old "Satisfactory."

My overall score was 88.

How did they arrive at that?

Over the course of the school year
teachers are evaluated by their supervisors. Using the [[http://danielsongroup.org/framework/][Danielson
Framework]] for teaching. I consider the Danielson stuff bunk and have
yet to be observed by someone who knows my subject area (Computer Science)
but I do have a fair supervisor who is supportive of her teachers.

I scored 58 out of 60.

The rest of the rating comes from standardized tests. Let me once
again go on record to state that basing teacher ratings on student
scores is asinine but it's actually worse. For teachers like myself
who don't teach regents courses, our scores come from school composite
grades. The city/state have super secret formulas that, incidentally
are figured out after the results are in to map my schools regents
results onto my evaluation grade. Yep, 40% of my rating is based on
students I haven't taught taking exams in subjects I don't teach.

The end result? We were awarded 30 out of 40 points.

The end result 58+30=88. 

So, since my kids didn't show growth on history and English regents,
I'm a run of the mill teacher. 

I think it's time to find another profession.





