#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Coding schools - or why I chose NYCDA
tags:  
---
#+end_html

* 
Some of you might have noticed that a few months ago, I decided to
affiliate myself with [[http://nycda.com][The New York Code and Design Academy]] or NYCDA. I
took on the role of "Academic Director, Youth Programs." It's a part
time gig, at least for now and I'm helping them develop their programs
for middle and high school students.

Why did I choose them?

There are a number of coding schools with varying levels of hype
around them. At their core, all are workforce programs. They take
people with little or no programming background and after a few months
of intensive training, they ship them off as web devs or the like.

* 
I have friends at many of these coding schools and related programs so
what was different about NYCDA that made me decide to work with them?

They know who they are, they know what they do, they know where they
want to go, and we all feel I can help them get there.

* 
Let me explain.

Most coding schools follow the same mold.

For one reason or another, a founder decides to start teaching a
class. This works pretty well so it starts to grow into a
business. For many of these coding schools, the teaching staff comes
from the program's own graduates.

The key point here is that most coding schools have little to no
interaction with real, experienced educators.

So, why do they work? Well, to start, there's plenty of low hanging
fruit. Right now, as these programs are in high demand,  programs can
cream top applicants. 

Many programs also have applicants complete
pre-work - that is a program of self study before starting the coding
school. This pretty much ensures that your classes are going to be
composed of hard working, intelligent self starters - that's a recipe
for a successful student body.

Given the student population and the fact that the skill set for an
entry level programmer can be taught fairly formulaicaly, it's a recipe
for success.

Now, I don't mean to imply that these schools are bad or doing bad
things - all of them are taking people and giving them a chance at a
new career. It's good and it's important. Even more so for
organizations that provide a step up for the have nots.

Teaching kids is another matter. 

For adults you're teaching a specific skill set for a specific job
market. For kids, you're setting a foundation and opening doors. You
can't just take your adult model and apply it to kids. Well, you can,
and it will even look good, but it won't have real substance.

That's what impressed me about NYCDA - when [[https://twitter.com/jeremysnepar][Jeremy]] came to me it was
clear - they knew what they did and what they did well. He also knew
that as they ramp up their youth offerings, it was important to
involve real, experienced educators - that it was about having true
expert teachers even more than it was curriculum. He understood that
while NYCDA is doing a great job, how much better could it be to
include CS educators who have been sending kids into industry
successfully for years.

I was even more delighted when my partner in crime JonAlf
Dyrland-Weaver - one of the best teachers I know, CS or otherwise,
agreed to teach one of our NYCDA youth courses this semester.

NYCDA is the only coding school working to bring the best teachers out
there to their youth programs.

That's why I joined on and that's why I'm really excited for the
programs we're going to roll out.



