#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Reunions, StuyCS and community
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

* 
In a few hours Devorah and I will be off to our thirty year high
school reunion. It's going to be a boat ride - reminiscent of those
excursion day trips to Bear Mountain that Stuy had back in the day.

Having taught CS at Stuy for the last twenty plus years, I've also
been invited to my share of reunions as a teacher. Sometimes the
current crop ask me about the reunions and how they compare to mine. I
usually say that the reunion that I just went to was pretty much the
same as my high school reunions just that I knew more people at the
reunion that wasn't my class.

I guess that makes sense -- as a teacher I work with and get to know a
large swath of students over their careers - when I was a student I
was pretty quiet and fairly asocial. I had friends, but not a huge
amount. Since 1984 I've only kept in touch with a few. Ben, Bill,
John, more recently, Eliza and Steve. There are others would have like
to have stayed in touch with but life happens.

As it turns out, while each year is different, all the reunions I've
been to have had a similar vibe. Similar clicks, similar groups, and similar
conversations. I guess that's what happens when you put a bunch of
smart people interested in a range of things in a room together. 

Funny thing is, I don't think the Stuy Vibe is unique to Stuy. I'd bet
that, if you permit me to posit, that Bronx Science reunions are
largely similar and if we put some Science alums in a Stuy reunion and
the conversation was not Stuy specific, we probably wouldn't spot the
interlopers.

I also had another reunion of sorts earlier in the week. As many of
you know, I maintain our StuyCS Alumni group or family, sometimes
called the StuyCS mafia. We had our latest meetup this past Wednesday
Around 60 Stuy alums, most of whom are my former students but some
from '84 and even before gathering together sharing food, drink,
stories, and fun. At the end of the evening I was chatting with Peter
and Ilya. We spanned 25 years of Stuy but we're all part of the same
family. Incidentally, if anyone reading this is in Tech and a Stuy
grad, head over to [[http://family.styucs.org][http://famiy.stuycs.org]] fill out the form and join
the family.

I've been thinking about my Stuy class and the StuyCS family a lot
recently. Probably because I see that the end of the Stuy portion of my
career is close at hand. The thing I've realized is that my Stuy isn't
the building on Chambers street nor is it the one on 15th. It's my
graduates, who have become my friends and my classmates that started
that way. It's like minded interesting people who do interesting
things and it's about the type of kid that grows into that type of
person.

Looking forward to reconnecting with some of those people in a few
hours and meeting some that I never knew before.




