#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Teachers, Rockstars, and the Godfather
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html


In a [[http://blog.acthompson.net/2014/12/tech-companies-and-computer-science.html][recent post]], [[https://twitter.com/alfredtwo][Alfred Thompson]] referred to an [[http://blog.acthompson.net/2012/12/advice-to-microsoft-education.html][earlier post]] where he
mentioned rock star CS teachers. That's a term I've heard thrown
around a lot in the past few years. I've heard some of my graduates
referred to as rock stars - top tech people, and in fact I've seen
some of them courted for positions in a manner that a rock star might
be accustomed to. I've periodically referred to some of my colleagues
as rock stars, but I don't know if the term really fits. 

So, how else are us teacher folk referred to? More than once I've been
called [[http://avc.com/2014/04/ship-st-josephs-a-summer-coding-program-in-nyc/][the godfather of K-12 CS education in NYC]]. Maybe because I've
been in the game so long or maybe because a friend once coined the
phrase "StuyCS Mafia" to refer to my graduates. It's flattering, but
like rock star, it doesn't quite fit the bill. Don Corleone rose to
power through both fear and respect. I certainly hope I'm not feared
and while I do believe that the people whose opinion I care about
respect me, it's far from universal.

So, where does that leave teachers like me, or more so, teachers I
aspire to be like?

Not the godfather and not rockstars.

We're bluesmen. 

Huh?

Well, the bluesman's got the chops that the rock star may or may not
have. In fact, the rock star always talks about how the bluesman was
his greatest influence and inspiration.

But, the rock star gets the accolades and the attention while the
bluesman toils in relative obscurity tending to his craft and if
acknowledged it's well after his career has ended.

So, there you have it. The best teachers I know are not rock stars,
they're bluesmen all about honing their craft and inspiring their
students.

One of the things Alfred talked about in his post is the top down
influence on CS education. On the one hand, it's brought attention to
bear but on the other hand it's being driven by people who don't
really get education.

The same can be said for the overall recent big money influences on
education.

We'd be much better off if those in power stopped playing rock star
and started listening to the bluesmen.

