#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: The new SAT - the more things stay the same 
tags:   SAT Test preparation College Board 
---
#+END_HTML

#+BEGIN_HTML
<style>
div.center {text-align:center;}
.large {font-size:200%}
</style>
#+END_HTML

#+BEGIN_HTML
<div class="large">
<b>Plus ça change, plus c'est la même chose</b>
</div>
#+END_HTML

The more things change, the more they stay the same.

Last week we heard all about the new SAT. Going back to 1600 points,
writing optional, and reworking the verbal section.

Immediate responses ranged from the usual fact that SAT doesn't correlate
with college success to the idea that the motive was not to improve
the test but rather to recapture market share from the ACT.

Personally, I'm not a fan of the test but I do see the desire to have
some consistent measure across students and schools. While an "A"
might say something about perseverance and hard work, the value of
one school's "A" is not necessarily the same as the value from
another.

But that's not what I wanted to write about.

A big criticism of the SAT is the fact that it can be prepped for and
thus gives a huge advantage to students and families of means. The
test can be gamed, one can take prep courses, hire private tutors,
etc.

As I said at the top...

Hot on the heels of the new SAT came the announcement that Khan
Academy will be offering [[https://www.khanacademy.org/sat][free prep for the new SAT]]. That sounds
terrific. 

I read it differently. I'm all for free educational materials being
universally available, but if Khan Academy can indeed offer test prep
for the new SAT then so can everyone else and people of means can
and will avail themselves of the Khan Academy material plus a wealth of other
resources.


So, new SAT but nothings changed.

