#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: What makes a great manager? - Open praise for my team
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

Today was the last day of SHIP 2015, CSTUY's summer immersion
program. I was blown away by the projects. The shipmates and the
stewards all did tremendous work.

All through the reception parents would come up to me and rave about
the job I did with the program. They'd thank me, tell me how exited
their child was every day, how proud they were of what they were
learning and on and on.

I of course nodded and told them that "yep, I'm that good."

No. Seriously.

First I thanked them and then told them the secret. 

I forget who said this but some coach or manager was one asked "what
makes a great manager?" His answer: "Great players."

I explained to the parents that I've been fortunate enough to be
surround by amazing teachers and that's what makes our program
special. We've got the best program because we've got the best
teachers. The best thing I can do is point them in the direction of
the kids and get out of the way.

So this post is an open thank you and congratulations to JonAlf, Sam,
Topher, and Yulia on yet another job well done. Four amazing CS
teachers. There's been a lot of discussion in the online CS communities
about CS teachers being isolated and not having resources but I am
fortunate in being surrounded by you four. I can't think of another
team that I'd rather "go to war" with.

Now, I don't want to leave out the other amazing players that made
SHIP a success. Chris, Marlena, Stanley, and Valeriy. Chris, Marlena,
and Stanley - you allowed us to give the individual attention we
needed for this program and students and parents sang your praises and
Valeriy, you were able to show the stewards stuff far beyond what I
could have.

And to all our Stewards - your impact on the shipmates was also so
critical to the programs success and that doesn't even mention your
projects which blew me away.

So to everyone, congratulations, job well done. 
