#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: State test scores - don't fall into the trap
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

** Test results are in:

The other week, the NY State [[http://www.nysed.gov/news/2014/state-education-department-releases-grades-3-8-assessment-results][third through eight grade high stakes
test results]] were released. This was immediately followed by the usual spin an posturing.
The +reformers+ privatizers
would claim things like "These charter schools did better than those
public schools" while people like me would say "Those charter schools
have different populations" and so on.
* 
As you know, I've never bought into the "miracle school" rot and my
friend and colleague [[https://twitter.com/garyrubinstein][Gary Rubinstein]] has done a great job at debunking
many of these schools with the so called "secret sauce."

When the results came out, I got caught in the trap. I started to cite
the reasons why the charter schools with phenomenal results are not
really so wonderful. One can look at:
- Attrition rates
- Test prep
- Lack of back fill
- and more.

** The Trap 
So, what's the trap? We shouldn't even be acknowledging the validity
of these exams.
* 
These are the 3-8th grade exams so I don't know that much about them,
but I do know that:
- They're not made by teachers.
- "Cut scores" are made after the fact - that is, the powers that be
  can **arbitrarily** decide what passing is.
- The exams **can't** be used to drive instruction. 
- Exam questions are a tightly held secret.

There are probably more, but I can't think of them now.

So exactly what is the value to the students and how do we know what
these tests are testing?

What it really comes down to is that we don't trust our teachers. If
we did, we wouldn't be giving statewide tests.

** Closer to home
What I do know more about are regents exams and they're just as
ridiculous.

Public schools ship out their tests for grading while charters grade
their own. Any wonder why some charters report better results?

The exams also range from being reasonable assessments to
ridiculous. I remember one year there was a proof on the regents where
the question gave the statements and reasons and the student had to
put them in order. Another year, they had to match the reasons to the
statements. Both ridiculous. Other years, the proof questions are in
my opinion reasonable.

Just as with the 3-8 grade tests, teachers can't use these exams to drive
instruction because they're given at the end of the year but at least
the questions aren't sealed so the following year teacher has some
clue. On the other hand, the "cut score" is again made after the
fact. Ever wonder why test scores are usually up during election years?

* 
And of course, in some cases, the tests just miss the point. At Stuy,
most of our ninth graders take a class that is usually called Geometry
and the state regents exam is called the geometry regents and is all
about Euclidean Geometry. The problem is, the course is really all
about logic and deductive reasoning using Euclidean Geometry as the
platform. This is of course missed on a standardized exam.

** The point:  
The big point here is that as a nation we don't trust teachers. By the
time we get to the end of the semester, I know what my kids know and
generally how they will do on exams, projects, papers and the like. I
have a good idea as to if they've mastered what I've been trying to
teach.

Instead, large amounts of taxpayer dollars are going to private
companies, placing kids under great stress while narrowing their
curricular possibilities and using junk science to remove good teachers.








