#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: Teachers - boy do we suck!!!!
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html
* 
Today was a "professional development day." That means that instead of
teaching, we were supposed to work on our craft. 

Rather than the normal nonsense - forcing CS teachers to sit through
common core math lectures or how to use the latest calculator, our
host principal, Randy Asher, of Brooklyn Tech let us do our thing. 

Basically, it was a bunch of CS teachers from two schools - Stuy and
Brooklyn Tech, talking shop for most of the day. 

Given the ridiculous "professional development" we're subject to weekly
at Stuy, it was a welcome change.

We talked about a number of issues:

- How difficult concepts like iteration can be to actually teach.
- How retention is a real issue.
- How we have to deal with a range of students with a range of
  interests.
- What happens when we have a kid who finds out they're less
  interested in CS than they thought.
- How do we create a comfortable setting for a diverse population.

and more.

I mean, really - all we do is talk about how hard it is to teach CS.

* 
Contrast that with every after school, summer, drop in, coding school
and program. They seem to:

- Teach kids to be software developers just like adults in the course
  of a summer.
- Teach kids how to make we apps in N weeks.
- Leave kids more prepared for the APCS A exam than kids to take the
  course.
- Solve the diversity problem.

Seeing how much and how well all these non-educators can do with kids
vs what we were talking about I can only conclude that us teacher folk
are pretty lousy.

On the other hand, us real teachers have to pay attention to to
little things like long term retention and success and can't just
parade out a few nice stories and outlier results.

Give me a real teacher any day.

I've written a bit on my concerns with drop in programs before [[http://cestlaz.github.io/2015/05/07/learning-takes-time.html#.VjlSyd8Sr0o][here]], [[http://cestlaz.github.io/2015/08/17/setting-up-to-fail-cs.html#.VjlSsd8Sr0o][here]], and
[[http://cestlaz.github.io/2015/10/12/nycda.html#.VjlSqd8Sr0o][here.]]

I remember a few years ago I was talking to someone about all the CS
Ed hype we were seeing. We both noted that many of the people doing
the best work are so busy doing that work that they can't spare the
time to generate the hype.

I was with a bunch of those people today.






