#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: CS4ALL, TFA and Education Reform
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html 
* 
This past weekend was Teach for America's 25th Anniversary summit. I'm
not affiliated with TFA in any way and I'm pretty open about my views
on the organization but more on that later.

Watching the tweet streem, I noticed that I actually knew a bunch of
people attending the summit. Mostly people involved in the CS4All,
learn to code CS education movement. For the most part, I'm guessing
they're TFA alums.

The sobering fact was that other than my friend and former colleague
[[https://twitter.com/garyrubinstein][Gary Rubentein]], none of the people I knew at TFA25 were actually
teachers. Gary, in addition to being a tremendous teacher has taken it
upon himself to dig into "miracle schools" and similar claims. It's
led him to become a critic of TFA.

So, I know a number of people who have been in TFA and I don't doubt their
sincerity but I have to say, I'm not a fan.

A few weeks training does not a teacher make but that's just the tip
of the iceberg. The TFA members, are by an large out of the classroom
after their comitement. Take a look at their page, [[https://www.teachforamerica.org/teach-with-tfa/after-the-corps][after the
corps]]. Only one of the highlighted individuals is actually still a
teacher.

TFA will probably claim that their alums go into "educational
leadership." Ok, so people who were barely in the classroom for a cup
of coffee is now driving educational policy.

Not good. 

What are some of the things coming out of TFA and the greater reform
movement?

- Scripted delivery of instruction
- A revolving door of teachers
- Devaluing experience
- The misguided emphasis on standardized tests
- Worse, using them to evaluate teachers.

It's pretty easy to find a laundry list of criticisms online.

Any of my regulars know my feelings - that the reform movement is all
about privatization and is doing great harm to this country. As far as
I can tell, TFA is a big part of that.

So, where am I going with all of this?

If you look, you'll notice similarities between aspects of the K12 CS
Education movement and the education reform movement.

Both get big pushes from industry.

Many (but not all) of the players in both are run by well meaning, connected people
with little to no teaching experience, little to know tech experience,
or neither.

Both are concerned with "winning." By that I mean, getting to their
goal and getting there fast. Scale scale scale. This is well
intentioned but any educator worth their salt will tell you that real
education and program building takes time.

Both are proponents of scripted lessons with minimal training. Maybe
not in word, but in deed. No, a few weeks over the summer is not
sufficient.








