#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil
#+begin_html
---
published: true
layout: post
title: VamVoom - Turning teachers into rubble
tags:  
---
#+end_html

#+begin_html
<style>
div.center {text-align:center;}
</style>
#+end_html

Earlier today I saw a friend's Facebook post questioning the sanity of
common core math. He had an issue with the way his daughter was being
forced to work out problems. A few of us chimed in with our low
op pinion on Common Core, others said they thought it was a good
idea. I think the fact that my buddy was questioning it is a major
strike against CC. This guy isn't just a friend, he's a math
teacher. Maybe the best one I know. In fact, he's the teacher I aspire
to be. If he's got a problem with how math is taught, he's probably right.

I made a comment also referring to VAM - the idea that teachers should
be evaluated by "Value added Measures" - that is, student test
scores. Another friend asked about it. I thought I'd write my response
up here.

This is just my opinion - I've read a number of pieces over the past
couple of years and the facts to back up any assertions I'm making
should be pretty easy to find by searching the web.


** The idea

VAM is all about evaluating teachers based on standardized tests. In
our case, we're talking NY State common core and regents exams. The
idea is to tie teacher ratings, and in some cases licensing to these
tests.

** The exams

Let's start with the problems with the exams. There's been a fair
amount of discussion over the past couple of years with regards to age
appropriateness and over testing. I'm not going to talk about
them. Let's just look at two things.

**** The gag order
  Teachers aren't allowed to talk about common core tests. The
questions, scoring, grading - everything is a secret.  Methinks
Pearson and NY State has something to hide. The party line is that
then questions can be reused - I'm calling BS on this.

I've been teaching 25 years. I give about 12 exams a year per class
plus quizzes, homework, and other assessments. None of them are secret
and somehow I manage as does every other teacher. 

By keeping everything a secret there's no accountability. Politicians
love to talk about accountability and transparency as long as it's for
others.

**** The scoring
Back in the day, regents exams were given and scored. Old exams were
public as was the scoring. If you got over a 65 you passed. 

Now, your exam is graded and then only after the fact, when the
numbers are in, does the state decide how to map raw scores to final
grades. Basically, the state can decide how many kids pass and by how
much and they do this after the fact. 

Sound fishy and susceptible to political influence?

** The evaluations

So, the exams that VAM's based on are already suspect. Let's dig
further. At Stuy, 40% of teacher evaluations are from standardized
tests. If you teach one of the magic subjects - English, Math, maybe
History - 20% of your results are based on your students results and
20% on the school or departmental results.

On the other hand, if you're like me and don't teach regents classes,
40% of my rating is based on exams in subjects I don't even teach.

Even if you could evaluate a teacher based on student exams, surely
you can't judge a computer science teacher based on another teacher's
students English exam scores.

On top of this, the formula is another one of those state
secrets. It's not public and it's worked out after the fact. The state
can basically look at all the numbers and then decide where to put the
cutoffs. 

** More problems

They abound. Here are a few:

Just about all of my kids do very well on the AP Computer Science
exam. Am I a good teacher because they all do well or a bad one since
they don't improve.

What about the kid that doesn't do particularly well but ends up
ultimately becoming a computer professional. I've had a number of
graduates that fit this bill that have credited me with setting the
spark. According to the system those students are failures as am I. 

What about kids that don't have the same teacher all year? Those that
already know the subject? Family factors? 

On top of this, people, like my friend and colleague Gary
Rubinstein have shown that VAM scores vary wildly and there have been
numerous reports showing that evaluating teacher based on student test
scores doesn't work and is just a bad idea.

** The bottom line

VAM is just another reason I can't recommend teaching to pretty much
anyone. 

Teacher's aren't against being evaluated, we just want a fair and
meaningful evaluation and more importantly a structure that can help
us do better. 


** The title

So, for the title, I keep seeing Vavoom - a character from "Felix the
Cat" that could level mountains with a single VAVOOM

#+begin_html
https://www.youtube.com/watch?v=gtZ_0gANyaY
#+end_html
